### ISSUE TITLE
Check that GitHub Actions are updated by dependabot

### ISSUE THREAD

**Issue by ccamel** [okp4/actions#3]
We really want to keep all the workflow templates (contained in `./src`) up to date by [dependabot](https://github.com/dependabot) as this repository is a collection of ready-to-use GitHub Actions.

Unfortunately it seems like it does not work (anymore), as reported by [dependabot/dependabot-core#4899](https://github.com/dependabot/dependabot-core/issues/4899). 😢

The current valid configuration is: 

```yaml
  - package-ecosystem: github-actions
    directory: /src
    schedule:
      interval: daily
    open-pull-requests-limit: 2
    reviewers:
      - amimart
      - ccamel
    assignees:
      - amimart
      - ccamel
```
